language: scala
services:
  - docker
cache:
  directories:
    - $HOME/.sbt # sbt
    - $HOME/.m2 # Maven repository
script:
  - sbt -Dhive.jdbc.version=upstream assembly
  - sbt -Dhive.jdbc.version=upstream test
