sudo: false
language: scala
cache:
  directories:
    - $HOME/.sbt # sbt
    - $HOME/.m2 # Maver repository
    - $HOME/.sdkman
script:
  - cd ..
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.222-zulu
  - sdk install maven 3.6.1
  - sdk install sbt 1.2.8
  - sdk install scala 2.11.12
  - sdk install spark 2.4.0
  - git clone https://github.com/kamu-data/hive
  - cd hive
  - git checkout release-1.2.1-spark2-kamu
  - mvn -Phadoop-2 -DskipTests -Psources install
  - cd ..
  - git clone https://github.com/kamu-data/kamu-core-ingest-polling
  - git clone https://github.com/kamu-data/kamu-core-manifests
  - git clone https://github.com/kamu-data/kamu-core-transform-streaming
  - cd kamu-cli
  - sbt assembly
