dist: xenial
language: scala
jdk:
  - openjdk8
scala:
  - 2.11.12
services:
  - docker
cache:
  directories:
    - $HOME/.sbt # sbt
    - $HOME/.m2 # Maven repository
script:
  - sbt -Dhive.jdbc.version=upstream assembly
  - sbt -Dhive.jdbc.version=upstream test
