[package]
name = "kamu-cli"
version = "0.1.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"
default-run = "kamu-rs"

[[bin]]
name = "kamu-rs"
path = "src/cli/main.rs"

[lib]
name = "kamu"


[dependencies]

# Serialization
flatbuffers = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"

# UI
clap = "*"
indicatif = "*"

# Utils
indoc = "*"  # Unindenting multi-line strings
