apiVersion: 1
kind: DatasetSnapshot
content:
  id: my.covid-19.federated
  source:
    kind: derivative
    inputs:
    - hk.gov.data.covid-19.eng
    - ph.gov.covid-19
    transform:
      kind: sql
      engine: flink
      query: >
        SELECT
          'hk.gov.data.covid-19.eng' as source_dataset,
          case_no,
          report_date,
          onset_date,
          gender,
          age
        FROM `hk.gov.data.covid-19.eng`
        UNION ALL
        SELECT
          'ph.gov.covid-19' as source_dataset,
          case_no,
          report_date,
          onset_date,
          gender,
          age
        FROM `ph.gov.covid-19`
  vocab:
    eventTimeColumn: report_date
