[package]
name = "kamu-adapter-graphql"
version = "0.102.2"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
# Kamu
dill = "~0.3"
opendatafabric = { path = "../opendatafabric" }
kamu = { path = "../kamu-core" }

# HTTP
# TODO: Remove from this crate
reqwest = { version = "*", features = ["json"] }

# GraphQL
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }

# Utils
indoc = "*"
chrono = "*"
# TODO: Using git version until v16 is released containing this fix https://github.com/apache/arrow-datafusion/pull/4530
datafusion = { git = "https://github.com/apache/arrow-datafusion", rev = "975ff15b25bdfe198db8c5b440f08cca45b2f482" }  # TODO: Currently needed for type conversions but ideally should be encapsulated by kamu-core
futures = "*"
serde = "*"
serde_json = "*"
# tokio = { version = "*", features = ["macros"] }
# url = "*"


[dev-dependencies]
tempfile = "*"
tokio = { version = "*" }
