[package]
name = "kamu"
version = "0.82.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"
license-file = "../LICENSE.txt"

[features]
skip_docker_tests = []

[dependencies]
dill = "~0.3"
# dill = { path = "../../dill" }
opendatafabric = { path = "../opendatafabric" }
container-runtime = { path = "../utils/container-runtime" }

# Domain
chrono = { version = "*", features = ["serde"] }
url = { version = "*", features = ["serde"] }

# Serialization
hex = "*"
serde = { version = "*", features = ["derive"] }
serde_with = "*"
serde_yaml = "*"
json = "*"

# Ingest
flate2 = "*"  # GZip decoder
fs_extra = "*"  # Copy files with progress, get directory sizes
curl = { version = "*", features = ["http2", "protocol-ftp", "static-curl", "static-ssl"] }  # TODO: reconsider static linking
curl-sys = "*"
zip = "*"
ringbuf = "*"

# Data
arrow-digest = "*"  # Data hashing (in-house library)
datafusion = "*"  # Reading data + SQL
digest = "*"
sha3 = "*"

# Repositories
bytes = "*"
futures = "*"
tokio = { version = "*", features=["fs"]}
tokio-util = { version = "*", features=["codec"]}
rusoto_core = {version = "*", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "*", default_features = false, features=["rustls"]}

# Utils
async-trait = "*"
async-recursion = "*"
cfg-if = "*"  # Conditional compilation
glob = "*"  # Used for glob fetch
rand = "^0.8"
regex = "*"
indoc = "*"  # Compile-time unindent
itertools = "*"
libc = "*"  # Signal names
pathdiff = "*"  # Relative paths
thiserror = "*"  # Structured error derivations
tracing = "*"
tempfile = "*"
walkdir = "*"

[target.'cfg(unix)'.dependencies]
users = "*"  # For getting uid:gid

[dev-dependencies]
filetime = "*"
env_logger = "*"
test-log = { version = "*", features = ["trace"] }
tracing-subscriber = { version = "*", features = ["env-filter"] }
