[package]
name = "kamu"
version = "0.1.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
# Domain
chrono = { version = "*", features = ["serde"] }
intervals-general = "*"
rust-crypto = "*"  # Data and metadata hashing

# Serialization
flatbuffers = "*"
serde = { version = "*", features = ["derive"] }
serde_with = "*"
serde_yaml = "*"

# Ingest
url = "*"

# Utils
rand = "*"
regex = "*"
indoc = "*"  # Compile-time unindent
thiserror = "*"  # Structured error derivations
tempfile = "*"
