[package]
name = "kamu"
version = "0.33.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[features]
skip_docker_tests = []

[dependencies]
opendatafabric = { path = "../opendatafabric" }

# Domain
chrono = { version = "*", features = ["serde"] }

# Serialization
hex = "*"
serde = { version = "*", features = ["derive"] }
serde_with = "*"
serde_yaml = "*"

# Ingest
url = "*"
flate2 = "*"  # GZip decoder
fs_extra = "*"  # Copy files with progress, get directory sizes
curl = { version = "*", features = ["http2", "protocol-ftp", "static-curl", "static-ssl"] }  # TODO: reconsider static linking
curl-sys = "*"
zip = "*"
ringbuf = "*"

# Utils
cfg-if = "*"  # Conditional compilation
glob = "*"  # Used for glob fetch
slog = "*"
rand = "*"
regex = "*"
indoc = "*"  # Compile-time unindent
itertools = "*"
signal-hook = "*"
thiserror = "*"  # Structured error derivations
tempfile = "*"

[target.'cfg(unix)'.dependencies]
users = "*"  # For getting uid:gid

[dev-dependencies]
kamu-test = { path = "../kamu-core-test" }
filetime = "*"
parquet = { git = "https://github.com/apache/arrow" }
