[package]
name = "kamu-test"
version = "0.30.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
kamu = { path = "../kamu-core" }

chrono = { version = "*", features = ["serde"] }
url = "*"
serde_yaml = "*"
