[package]
name = "kamu-cli"
version = "0.78.2"
description = "Decentralized data management tool"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"
readme = "../README.md"
license-file = "../LICENSE.txt"
homepage = "https://github.com/kamu-data/kamu-cli"
repository = "https://github.com/kamu-data/kamu-cli"
keywords = ["cli", "data", "collaboration", "pipeline", "management", "provenance"]
categories = ["command-line-utilities"]

[features]
skip_docker_tests = []

[dependencies]
dill = "~0.3"
# dill = { path = "../../dill" }
opendatafabric = { path = "../opendatafabric" }
kamu = { path = "../kamu-core" }
kamu-adapter-graphql = { path = "../kamu-adapter-graphql" }
container-runtime = { path = "../utils/container-runtime" }

# UI
read_input = "*"  # Basic user input
chrono-humanize = "*"  # Human readable durations
clap = "*"
clap_complete = "*"
console = "*"  # Terminal colors
humansize = "*"  # Human readable data sizes
indicatif = "*"  # Progress bars and spinners
minus = { version = "=4.0.1", features = ["static_output", "search"] }  # Terminal paginator  TODO: https://github.com/arijit79/minus/issues/56
num-format = "*"  # Human-readable number formatting
prettytable-rs = "*"  # ASCII table formatting
webbrowser = "*"  # For opening URLs in default system browser

# Web API & UI
http = "*"
hyper = "*"
tower = { version = "*" }
tower-http = { version = "*", features = ["trace", "cors"] }
axum = "*"
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }
async-graphql-axum = "*"
serde_json = "*"

# Config
merge = "*"
serde = { version = "*", features = ["derive"] }
serde_with = "*"
serde_yaml = "*"
duration-string = { version = "*", features = ["serde"] }

# Tracing / logging / telemetry
tracing = "*"
tracing-appender = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
tracing-log = "*"
tracing-bunyan-formatter = "*"

# Utils
async-trait = "*"
chrono = "*"
cfg-if = "*"  # Conditional compilation
glob = "*"  # Used for path completions
datafusion = "^5"  # Reading data + SQL
dirs = "*"
indoc = "*"
itertools = "*"
libc = "*"  # Signal names
regex = "*"
shlex = "*"  # Parsing partial input for custom completions
signal-hook = "*"  # Signal handling
tokio = { version = "*", features = [] }
tempfile = "*"
thiserror = "*"  # Structured error derivations
url = "*"
urlencoding = "*"


[target.'cfg(unix)'.dependencies]
users = "*"  # For getting uid:gid


[dev-dependencies]
rand = "^0.8"
indoc = "*"  # Compile-time unindent
parquet = "*"
env_logger = "*"
test-log = { version = "*", features = ["trace"] }
