[package]
name = "kamu-cli"
version = "0.1.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
kamu = { path = "../kamu-core" }

chrono = "*"
clap = "*"
console = "*"  # Terminal colors
glob = "*"  # Used for path completions
indicatif = "*"  # Progress bars and spinners
itertools = "*"
shlex = "*"  # Parsing partial input for custom completions
slog = "*"  # Logging
slog-async = "*"
slog-term = "*"
tempfile = "*"
thiserror = "*"  # Structured error derivations

# TODO: Move to core
parquet = { git = "https://github.com/apache/arrow" }

[dev-dependencies]
rand = "*"
