apiVersion: 1
kind: DatasetSnapshot
content:
  id: my.trading.holdings.market-value
  source:
    kind: derivative
    inputs:
    - com.yahoo.finance.tickers.daily
    - my.trading.holdings
    transform:
      engine: flink
      temporalTables:
      - id: my.trading.holdings
        primaryKey:
        - symbol
      query: >
        SELECT
          tickers.`event_time`,
          holdings.`symbol`,
          holdings.`cum_quantity`,
          holdings.`quantity` as `quantity`,
          tickers.`close_adj` * holdings.`cum_quantity` as `market_value`
        FROM
          `com.yahoo.finance.tickers.daily` as tickers,
          LATERAL TABLE (`my.trading.holdings`(tickers.`event_time`)) as holdings
        WHERE tickers.`symbol` = holdings.`symbol`
