[package]
name = "tools"
version = "0.0.0"
description = "Tools for managing this repo"

[[bin]]
name = "release"
path = "src/release.rs"

[[bin]]
name = "create-test-workspace"
path = "src/create_test_workspace.rs"

[dependencies]
clap = "*"
yaml-rust = "*"
toml = "*"
toml_edit = "*"
semver = "*"
url = "*"
