name: build
on:
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "images/**"
      - "**.md"
  # manual trigger
  workflow_dispatch: {}
env:
  RUST_BACKTRACE: "1"
jobs:
  lint_fmt:
    name: Lint / Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
        with:
          components: rustfmt
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  lint_deps:
    name: Lint / Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      - run: cargo install --locked cargo-deny
      - run: cargo deny check

  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      - uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: "0.19"
      # - uses: actions/cache@v3 # Source: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo
      - run: |
          echo '{ "kind": "CLIConfig", "version": 1, "content": {"engine": { "runtime": "podman" } } }' > ~/.kamuconfig
      - run: cargo build --features test_ftp
      - run: cargo test --verbose --features test_ftp
      - run: git diff
      - run: git diff-index --quiet HEAD # Ensure all generated files are up-to-date

  test_macos:
    name: Test / MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      # - uses: actions/cache@v3 # Source: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo
      - run: cargo build --features skip_docker_tests
      - run: cargo test --verbose --features skip_docker_tests

  test_windows:
    name: Test / Windows
    runs-on: windows-latest
    # Disabling until we investigate the cause of linker OOM crash
    # Issue: https://www.notion.so/CI-Windows-build-is-failing-with-linker-OOM-d6d2fc0cb71543d79ff79539f539c603?pvs=4
    if: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      # - uses: actions/cache@v3 # Source: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo
      - run: cargo build --features skip_docker_tests
      - run: cargo test --verbose --features skip_docker_tests
