name: build
on:
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "images/**"
      - "**.md"
  # manual trigger
  workflow_dispatch: {}
env:
  RUST_BACKTRACE: "1"
jobs:
  lint_fmt:
    name: Lint / Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
        with:
          components: rustfmt
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  lint_deps:
    name: Lint / Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      - run: cargo install --locked cargo-deny
      - run: cargo deny check

  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    env:
      KAMU_FEATURES: ftp
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      - uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: "0.19"
      # - uses: actions/cache@v3 # Source: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo
      - name: Configure podman runtime
        run: |
          echo '{ "kind": "CLIConfig", "version": 1, "content": {"engine": { "runtime": "podman" } } }' > ~/.kamuconfig
      - name: build
        run: cargo test --features $KAMU_FEATURES --no-run
      - name: pull test images
        run: cargo test --features $KAMU_FEATURES test_setup_pull_images
      - name: run tests
        run: cargo test --features $KAMU_FEATURES
      - name: check git diff 
        run: git diff && git diff-index --quiet HEAD # Ensure all generated files are up-to-date

  test_macos:
    name: Test / MacOS
    runs-on: macos-latest
    env:
      KAMU_FEATURES: skip_docker_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      # - uses: actions/cache@v3 # Source: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo
      - name: build
        run: cargo test --features $KAMU_FEATURES --no-run
      - name: run tests
        run: cargo test --features $KAMU_FEATURES

  test_windows:
    name: Test / Windows
    runs-on: windows-latest
    env:
      KAMU_FEATURES: skip_docker_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
      # - uses: actions/cache@v3 # Source: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo
      - name: build
        run: cargo test --features $KAMU_FEATURES --no-run
      - name: run tests
        run: cargo test --features $KAMU_FEATURES
