name: build
on: [push]
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
jobs:
  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1  # Uses rust-toolchain file
      - run: docker pull kamudata/engine-spark:0.8.1
      - run: docker pull kamudata/engine-flink:0.6.0
      - run: docker pull httpd:2.4
      - run: docker pull bogem/ftp
      - run: cargo test --verbose
  test_macos:
    name: Test / MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1  # Uses rust-toolchain file
      - run: cd kamu-core && cargo test --features skip_docker_tests --verbose
      - run: cd kamu-cli && cargo test --verbose
  test_windows:
    name: Test / Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1  # Uses rust-toolchain file
      - run: cd kamu-core && cargo test --features skip_docker_tests --verbose
      - run: cd kamu-cli && cargo test --verbose
