name: release-images-test
on:
  # Manual trigger
  workflow_dispatch: {}
jobs:
  build_images:
    name: Build Images
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == null
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with sample data
        run: |
          cd images/
          make kamu-base-with-data
          make kamu-base-with-data-mt
